### ISSUE TITLE
Retake Preview

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#10]
**_Can we show the buildings new state again before giving the user the option to retake the option?**_

**Flow**:
User selects option
Show City view again with building coloured in relative to answer chosen
Give user option to re take if not chosen optimal choice

**_We can achieve this without much effort right?**_

**Comment by formerhermit** [comment]
Also as a side note to this (adding in case another solution is more suitable), it came about because at the moment a wrong answer forces an automatic replay and the wider team suggested that this doesn't give the player any understanding of what happens with their city e.g. opportunity to see the building is still sad and grey, or chance to back out and play a different block.

**Comment by kbowerma** [comment]
@thomasgriffinx email

@invisiblepilot will mock up the pop up with the game piece

**Comment by kbowerma** [comment]
Here is Kim's  ( @invisiblepilot )    explanations and supporting pdf:

> 1- show the question on hover over city game piece 
> no image in question box here - image is already present / highlighted on hover and we don’t want to complicate the already image-heavy screen with more image pre-loading!
> 
> 2- show the actual game piece on question screen
> 
> 3- show the actual game piece in feedback popup 
> there are really only two possible states for the game piece here: acceptable and great. If the user gets the answer wrong, he must retake it or skip it, so no “wrong” state. The “gray” state only indicates an answer that has not been answered, so user can find them on the city screen
> 
> NOTE: IF we go this route, we will need a task to create the two possible images for each game piece, because the city view version of these vary widely in height and width = each piece will have to be manually re-sized for best display in the space allotted. I am reaching out to get a cost on this re-sizing task.

[Eli Lili Game Piece Concept.pdf](https://github.com/topcoderinc/umbrella_city/files/215315/Eli.Lili.Game.Piece.Concept.pdf)
