### ISSUE TITLE
rules and intro

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#11]
**Rules**
The city of Lillyville is an analogy for Lilly’s IT infrastructure, the buildings roads and transport links are representative of the servers, networks and clusters that make up our IT ecosystem.  Events which happen in the city are an analogy for events which happen in Lilly IT, and like the IT ecosystem, the city of Lillyville has grown reactively over the years; the government will need to begin to think strategically in order to remain popular with visitors, businesses and residents. We are all the architects in Lilly, and this is your opportunity to put the skills you have learnt in the IT Strategy training course to good use.

You are a city architect who has been employed to modernise the city, we’ve given you a starting budget, so spend this wisely! Click on grey buildings to invest in a block and play a scenario. There will be three answer options for any given scenario - a perfect answer, an OK answer and a poor answer. 

A perfect answer will return your investment, award a bonus AND get the best looking building on your map. Once you get the perfect answer, you have to move on.

OK answers won't incur a penalty but you won't get your investment back either.  You’ll refurbish a square on your map, but it won’t be as nice as a perfect answer, however you can play again if you’re willing to invest more money!

Poor answers will incur a penalty and you'll have to pay out again to do over! 

You will also see your map begin to change from grey to colour, and the more perfect answers you get, the more attractive your city will look.

The more answers you get perfect the more money you make, and the higher your position on the scoreboard will be. Titles are granted when monetary targets are achieved, to show that you’re progressing as an experienced architect. Once you’ve won a title, you can lose it if you start to drop below the score threshold, but we’re given you one “extra life” just to help you out.

**Introduction Popup Text**
Welcome to Lillytropolis! You are a city architect who has been employed to modernise the city, we’ve given you a starting budget, so spend this wisely! Click on grey buildings to answer questions and refurbish your city to a future state. The closer your choices are to the overall strategy, the more money you will earn. However, be warned that poor choices can also have consequences!

**Comment by formerhermit** [comment]
I've sent these over to the US team who will be reviewing and hopefully coming back with some feedback soon.

**Comment by RiteshTC** [comment]
Completed but not merged, as the rules contains references to Lilly, 
We would be creating the package from the org for challenges. 
will merge after completion of all challenges.

**Comment by formerhermit** [comment]
Did this work include the introduction popup that we discussed? I can see the rules in the demo org, but no popup (though I haven't started as a brand new user so this might be why?) @RiteshAppirio @kbowerma

**Comment by kbowerma** [comment]
Yes you are right I broke the popup to #40
