### ISSUE TITLE
Scoring rule

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#12]
**Starting Pot**
50,000 DollarPounds

**Scenario Prices**
The prices to play a scenario will range from 100-5000 depending on their difficulty.
## Scoring

| Answer | Payout | Details |
| --- | --- | --- |
| GOOD | Price + (price \* 0.72) | Get money back plus bonus of 72% |
| OK | None | No money back, no reward |
| BAD | Price \* -1.25 | No money back, penalty of 25% of price plus the price of the block |
## Title Bands

| Title | Score (From:) |
| --- | --- |
| City Janitor | 50,000 and below |
| Town Planner | 55,000 - 59,999 |
| Structural Engineer | 60,000 - 79,999 |
| Junior Architect | 70,000 - 89,999 |
| Competent Architect | 80,000  - 89,999 |
| Black belt Architect | 90,000 - 99,999 |
| Overlord Architect | 100,000 & up |

Titles are granted when monetary targets are achieved. Once at a title, players are allowed one 
wrong answer before their title will be affected. After this they can drop down a title band should 
they go under the score needed to be in that bracket. 

E.g At Town Planner, score at 56,000. Penalty and cost of scenario takes the player to 54,000. They 
retain their title if they get the next question right, but will end up on City Janitor if they get it 
wrong.

Players will not end up on the scoreboard until you have answered all the questions in the first 
release (?)

**Comment by kbowerma** [comment]
@Amazingstoke can you drop in title once you go below that amount or do you always retain your title

**Comment by formerhermit** [comment]
@kbowerma We think people should be able to lose their titles but Tom suggested having a free pass - so the first time you get a question wrong it doesn't count if you go under the threshold. I think this might be making stuff a little complex, but I agree having people going up and down titles constantly might be a bit rubbish.

**Comment by kbowerma** [comment]
For now we are going to straight up map the titles to the mapping table above,   see #20 for a place holder for future complex logic.  (like you get one round before you officially loose your title. )

**Comment by formerhermit** [comment]
Just FYI @kbowerma 

Given that all players start off with a positive budget, and once in game they will likely spend some of this budget, we will end up with scoreboard situations like this.

Place 23. Jo: 50,000 DP (Hasn't started playing)
Place 24. Tom 49,000DP (Has played already

Jo is above Tom, but has not started the game yet. We thought the best way of dealing with this was to not have players appear on the scoreboard until they have completed a question/scenario. Just wanted to clarify this.

**Comment by kbowerma** [comment]
@RiteshAppirio    I see you are working on this and it is looking good.   A wrong answer is subtract 2x the cost instead of 1.25x

**Comment by kbowerma** [comment]
@formerhermit   I think the leader board should only contain scores above the starting point.   What do you think?

**Comment by formerhermit** [comment]
@kbowerma Yeah, I'm good with this. I think in hindsight we've set the gains to be substantial enough for most people to end up over the starting value....

**Comment by formerhermit** [comment]
@thomasgriffinx did we want it so that the scoring goes into minus figures?

**Comment by ThomasGriffinx** [comment]
@formerhermit We did

**Comment by formerhermit** [comment]
Scoring works as requested, title bands also working fine. Close
