### ISSUE TITLE
no facility to limit questions (levels)

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#14]
We talked about this but it is not in the code,   Do we want to add it or not

**Comment by formerhermit** [comment]
@kbowerma Sorry Kyle, did we talk about this last night? Could you expand

**Comment by kbowerma** [comment]
No we did not.    Basicly if we have two cities loaded you can hit the next button and go back and forth at will.    Maybe that is ok or maybe we want to say you can't advance to the next one until you complete all the questions on the previous one.   Not super urgent but a decision we need to make

**Comment by ThomasGriffinx** [comment]
at the moment we are having conversations around using a trailer to frame the game, this would make the tutorial level redundant so lets sit on this, we can talk about it monday night

**Comment by formerhermit** [comment]
@kbowerma We've talked about this and @ThomasGriffinx and I want to start with the bigger city and make it so that people cannot progress onto the smaller one until the bigger city is complete. We won't be launching with a complete set of scenarios so this is likely to happen some time in the future.

**Comment by kbowerma** [comment]
We should be good to go then.  We have buildings for all the blocks on the big city.

**Comment by formerhermit** [comment]
Perfect! 
- Sent from my iPhone

**Comment by formerhermit** [comment]
Happy to close this one as we've decided on limiting the users to big city until it's complete
