### ISSUE TITLE
User Rank is not updated in the Game Board

### ISSUE THREAD

**Issue by RiteshTC** [topcoderinc/umbrella_city#15]
![currentrankisnotupdated](https://cloud.githubusercontent.com/assets/5771673/14434534/eafa5610-0030-11e6-8445-98c58cb1ed6d.png)
User Rank is not updated in Game board. It's hard coded to 999+

**Comment by RiteshTC** [comment]
Rank >= 1000 should be displayed as 999+. If the user rank is below the 999 figure, actual rank should be displayed.

**Comment by ThomasGriffinx** [comment]
@RiteshAppirio  @formerhermit  does this effect the searching of the leaderboard? So if I am 999+ does my name appear in the leaderboard when searched , or am I classed as un ranked?

**Comment by ThomasGriffinx** [comment]
I am just wondering, not a deal breaker

**Comment by RiteshTC** [comment]
@ThomasGriffinx ,Nope this doesn't affect user searching on leaderboard. Leaderboard only lists only the users, with more than minimum balance that is 50K

**Comment by formerhermit** [comment]
Tested, this is fine.
