### ISSUE TITLE
Validation of Blocks and Quadrants

### ISSUE THREAD

**Issue by RiteshTC** [topcoderinc/umbrella_city#18]
If a quadrant or block is missing (ie admin missed a sequence, the game doesn't work). Create a custom button validate on City, that checks if all quadrants, and blocks are in 
1) Proper sequence
2) No duplicates
3) Each quadrant has blocks
4) Blocks have stories and solution assigned.

**Comment by ThomasGriffinx** [comment]
@RiteshAppirio @formerhermit @kbowerma do we have an update on this one?

**Comment by RiteshTC** [comment]
@ThomasGriffinx , this may not be needed now, since we have the custom data loader to load records.
If you think, this will be valuable, I can get a challenge launched to get this done.

**Comment by formerhermit** [comment]
@ThomasGriffinx do we still need this? If not can we please close this one?

**Comment by ThomasGriffinx** [comment]
@RiteshAppirio @kbowerma @formerhermit  Ive found a fix for the problems we were having with the .csv files so the data loader solution should be fine, lets close this one
