### ISSUE TITLE
 [$50] Convert PDF to README

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#2]
Convert the pdf in the root dir to a readme.md file   The images can be pulled out and run from the wiki or an issue.

Please take off the up for grabs label, and assign the task to yourself.     You have 24 hour before you give it up.   Please create a pull request and change the label to read for review.    You should also submit the source code(readme is fine) into the challenge so the scoring engine is triggered

**Comment by kbowerma** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by kbowerma** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by kbowerma** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true

**Comment by kbowerma** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30053674/?type=develop&noncache=true

**Comment by kbowerma** [comment]
Don't worry about the borders and page numbers in stuff.   Just a basic markdown with pictures.

**Comment by AleaActaEst** [comment]
How can I assign it to me? (TopCoder handler is AleaActaEst)

**Comment by kbowerma** [comment]
@AleaActaEst   You should assign this issues to your github account.    I just tried to assign it to you but you github login did not show up.    Try assign to yourself with the link on the right.    Maybe you need to follow this repo or something

**Comment by inf3rum** [comment]
Ok will give it a try :)

**Comment by AleaActaEst** [comment]
Will give it a try

**Comment by AleaActaEst** [comment]
Looks like unless I am a collaborator I cannot assign it to myself :(

**Comment by AleaActaEst** [comment]
Can you assign me as a collaborator?

**Comment by kbowerma** [comment]
I will just assign it to me so people know if is not up for grabs.   I will also add a label called reserved and remove it if you don't complete this time tomorrow.

Thanks

Also you have been around the block with topcoder so after this is over I want to know how your experience is.

**Comment by AleaActaEst** [comment]
Thx! :)

**Comment by spiffyladd-career** [comment]
Is there any specific reason that you reserved it? It is an open challenge so why one should be given a fair chance...

**Comment by Eronana** [comment]
![install_umbrella_city_builder_game](https://cloud.githubusercontent.com/assets/9164153/14348749/2d1e69a2-fcf1-11e5-9e85-778c2a7eae9f.jpg)
![installation_complete](https://cloud.githubusercontent.com/assets/9164153/14348748/2d1de086-fcf1-11e5-8e69-cfa58935111b.jpg)
![launching](https://cloud.githubusercontent.com/assets/9164153/14348753/2dedab2c-fcf1-11e5-9ddf-68cd9c9b78e4.jpg)
![leaderboard](https://cloud.githubusercontent.com/assets/9164153/14348754/2df01b46-fcf1-11e5-90d0-1aeb8e49ad53.jpg)
![overall_code_coverage](https://cloud.githubusercontent.com/assets/9164153/14348752/2dbdab2a-fcf1-11e5-8b0a-5defc0650b21.jpg)
![play](https://cloud.githubusercontent.com/assets/9164153/14348750/2d8314e2-fcf1-11e5-8544-05585dbd0d5d.jpg)

**Comment by kbowerma** [comment]
@spiffyladd-career, even though this is a code challenge it acts more like a first to finish since the solution either works or not.      I don't want a bunch of people to waste their time if someone is already working on it and sure to win.   That is why I am giving them 24 hours to submit then it will go to the next if they don't complete.

**Comment by AleaActaEst** [comment]
How should I submit the change?
In the Forums?

EDIT: there are some typos in the document which I fixed but I did not proof read the whole text. also the images have not been included but it would not be hard to add those.
