### ISSUE TITLE
demotion

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#20]
look back at demotions,   from #12

**Comment by ThomasGriffinx** [comment]
we are sitting on this for a while and waiting to have another discussion.  It is friday and its not going to happen today :) @formerhermit

**Comment by RiteshTC** [comment]
This feature currently exists, by using a field called Streak. The title is only updated, when a player gives consecutive bad answers for 2 Blocks.

**Comment by formerhermit** [comment]
@RiteshAppirio Wow, that's really great to hear! This one has been giving me a headache.

**Comment by formerhermit** [comment]
This appears to be functioning fine. Closing
