### ISSUE TITLE
Salesforce: Umbrella City story and building preview

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#21]
We are super excited about our Salesforce Educational City Building game that you have helped us build.    For this challenge we would like to make a few cosmetic changes to help make the game flow better.    Basically from the city map we want to display the question in a hover over and when the user is presented with the question and gets the feedback the building is displayed as part of the question page and popup.
## Requirements
1.   As you hover over the city map, you will see the buildings (game pieces) that have questions that you have not answered get highlighted.     We now want to see the question pop up like in the image Below:
   <img width="1198" alt="screen shot 2016-04-12 at 2 00 21 pm" src="https://cloud.githubusercontent.com/assets/1180747/14472042/f81d1f86-00b6-11e6-8aed-b012241cb31b.png">
2.  Once the user selects the block (aka building aka game piece) the CB_Play page is open.   Currently the story has a generic icon of a couple of buildings.   We would like to change this icon to the actual game piece building in the best state see image below (Note the image that shows the game piece in the 'Ok' state but we want it in the best state which shows the green grass.
   <img width="1388" alt="screen shot 2016-04-12 at 1 27 53 pm" src="https://cloud.githubusercontent.com/assets/1180747/14471963/a58ea028-00b6-11e6-8123-b9fbc0e6af52.png">
3.   Once the user submits the answer the pop should also show the game piece in the state that matches their answer (the success should show the grass,  the 'Not Bad' should show just the building colored and the Oops should not show the building at all.   See the next three images:
   <img width="699" alt="screen shot 2016-04-12 at 1 28 02 pm" src="https://cloud.githubusercontent.com/assets/1180747/14471964/a5969af8-00b6-11e6-9a15-46535df23883.png">
   <img width="702" alt="screen shot 2016-04-12 at 1 28 12 pm" src="https://cloud.githubusercontent.com/assets/1180747/14471961/a58d41ec-00b6-11e6-9102-e0b1e4cea284.png">
   <img width="1392" alt="screen shot 2016-04-12 at 1 28 25 pm" src="https://cloud.githubusercontent.com/assets/1180747/14471962/a58e1824-00b6-11e6-89f3-d31676a79510.png">
## Setup

Go to this repo:   https://github.com/topcoderinc/umbrella_city   and follow the readme instructions there is some anonymous apex scripts that will help load some data for you.
## Submissions
1.  Please submit your code in a single zip file,  include the entire git directory including the .git folder so we can diff it.   Winners will be asked to submit a pull request.
2.  Please provide a quick video of your submission in action.   If you are not comfortable with spoken english please feel free to annotate your video.
3.  You are welcome to use the forums of this: https://github.com/topcoderinc/umbrella_city/issues/21 github issue to post questions.   We will be monitoring both.

Good Luck
kbowerma

**Comment by kbowerma** [comment]
<img width="1198" alt="screen shot 2016-04-12 at 2 00 21 pm" src="https://cloud.githubusercontent.com/assets/1180747/14472042/f81d1f86-00b6-11e6-8aed-b012241cb31b.png">

<img width="1388" alt="screen shot 2016-04-12 at 1 27 53 pm" src="https://cloud.githubusercontent.com/assets/1180747/14471963/a58ea028-00b6-11e6-8123-b9fbc0e6af52.png">
<img width="699" alt="screen shot 2016-04-12 at 1 28 02 pm" src="https://cloud.githubusercontent.com/assets/1180747/14471964/a5969af8-00b6-11e6-9a15-46535df23883.png">
<img width="702" alt="screen shot 2016-04-12 at 1 28 12 pm" src="https://cloud.githubusercontent.com/assets/1180747/14471961/a58d41ec-00b6-11e6-9102-e0b1e4cea284.png">
<img width="1392" alt="screen shot 2016-04-12 at 1 28 25 pm" src="https://cloud.githubusercontent.com/assets/1180747/14471962/a58e1824-00b6-11e6-89f3-d31676a79510.png">

**Comment by kbowerma** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30053759/?type=develop&noncache=true

**Comment by ThomasGriffinx** [comment]
Hey Guys, 
 When a grey building is clicked on from the map view, the piece that is shown in the circle  should exactly reflect the image that was clicked on.  At the moment all the images in the question circle icon are the perfect solution regardless of the state of the original building. 

Thanks :)
