### ISSUE TITLE
add four character class VF and Objects

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#23]
We need a pseudo namespace for char all caps per org requirements, what should we use?

**Comment by ThomasGriffinx** [comment]
CBGA is our chosen prefix, we have checked and it is not in use for anything else

**Comment by formerhermit** [comment]
Well it wasn't mine but I was outvoted....

**Comment by RiteshTC** [comment]
@kbowerma Let me know, if its okay to make this change in the demo org.

It will involve, deleting existing artifacts, and recreating them. Demo org will be unavailable for few hours to 1-2 days, while the change is in progress.

**Comment by RiteshTC** [comment]
@kbowerma I have merged the challenge code in the demo org. I will tackle this change tomorrow.

**Comment by kbowerma** [comment]
Ok, Thank @RiteshAppirio   it looks good so far.    @formerhermit  want to show off the demo to some people so let make sure we coordinate with here the outage with the namespace changes.    If it helps I can get another demo org set up.    I will also make sure I update the code in github today to reflect your latest changes.

**Comment by RiteshTC** [comment]
@kbowerma No issues, I can work in the changes in my dev org, and merge later. I will chatter again, when I have done the changes, so that we can schedule the downtime.

**Comment by kbowerma** [comment]
Ok thanks Ritesh

**Comment by RiteshTC** [comment]
@kbowerma This change has been done in my dev org and is ready to be moved to the demo org, along with other related fixes. Let me know, the downtime window.

**Comment by formerhermit** [comment]
@RiteshAppirio I and @ThomasGriffinx have no problem with a downtime window as soon as you like - we are holding off showing the demo org to anyone so as long as @kbowerma is ok with it, so are we :smile:

**Comment by ThomasGriffinx** [comment]
@RiteshAppirio  Hey , you can have all the downtime you need this week, you can push to demo org at your earliest convenience :) Thanks

**Comment by RiteshTC** [comment]
Great @ThomasGriffinx @formerhermit I will start the preparations for pushing the updated code.

**Comment by RiteshTC** [comment]
@ThomasGriffinx @formerhermit The changes have been deployed in the demo org, along with the sample scenario's. Please have a look when you get a chance.
