### ISSUE TITLE
Data Loader - Building Image

### ISSUE THREAD

**Issue by formerhermit** [topcoderinc/umbrella_city#26]
Just testing the data loader - have successfully used the sample data to create a city. Only thing is in the scenario popup and feedback box, the game piece doesn't show in the circle - see attached. Think data load challenge was before preview enhancement piece so might need an extra field for the game piece (building) image URL?
![issue](https://cloud.githubusercontent.com/assets/18323317/14702792/38700050-07a4-11e6-9396-fbe892d503ed.PNG)
![issueb](https://cloud.githubusercontent.com/assets/18323317/14702791/386a8148-07a4-11e6-9529-84fc311969a1.PNG)

?

**Comment by formerhermit** [comment]
@kbowerma We also noticed from the sample csv, there appears to be the same data plugged into the choice and into the feedback field? For example in above the option "Great City" also has the feedback "Great City". Do we need another value here for feedback text? Can only see solution text, no feedback text or answer text?
[CityDataSampleCSVFilea.txt](https://github.com/topcoderinc/umbrella_city/files/231950/CityDataSampleCSVFilea.txt)

Story Solution Option Row: Option,{city_unique_key},{quadrant_unique_key},{block_unique_key},{story_unique_key},{score},{Reward_amount},{**solution_text**},{solution_sequence}

**Comment by RiteshTC** [comment]
Both issues have been fixed in Development env, and will be migrated to demo org after approval.
Here is updated format of csv file (please rename to .csv from .txt, github doesn't like csv files)
[sampleCSV.txt](https://github.com/topcoderinc/umbrella_city/files/232973/sampleCSV.txt)

**Comment by formerhermit** [comment]
@RiteshAppirio @kbowerma I've played around with this and it looks to be working now and all the right fields are there. One question, if the file is CSV, what happens if some of the text strings contain commas - e.g. This is a question in the game, you must answer it - is there a way of disregarding that comma in the test string? Or should we use a different delimiter e.g. |
