### ISSUE TITLE
Check Test Classes and Code Coverage

### ISSUE THREAD

**Issue by RiteshTC** [topcoderinc/umbrella_city#29]

**Comment by ThomasGriffinx** [comment]
@RiteshAppirio do you have a full updated XML document including all test classes?

**Comment by RiteshTC** [comment]
Here it is
[package.txt](https://github.com/topcoderinc/umbrella_city/files/241736/package.txt)

**Comment by kbowerma** [comment]
@ThomasGriffinx,   I just updated the src dir in this repo so the package.xml should be correct.
