### ISSUE TITLE
Can we have temp access to Ritesh's Dev Org

### ISSUE THREAD

**Issue by ThomasGriffinx** [topcoderinc/umbrella_city#30]
Hi Guys

If you can provide me with the user name and password to Ritesh's dev , I can pull the game from it with mavens mate and re build it from source in a dev org , Myself and @formerhermit  can then review all the changes made here and sign them off. 

Mainly we need to be able to give the leaders a demo of the scenarios using data loader before we can sign off 

You can just give me temporary access just for today or tomorrow - long enough for me to do a pull 

Cheers

**Comment by RiteshTC** [comment]
Hi @ThomasGriffinx , I can deploy the changes in demo org, if I can get a downtime window. Please see. #23

**Comment by formerhermit** [comment]
Closing this as dealt with in other thread.
