### ISSUE TITLE
Minus Budget Formatting

### ISSUE THREAD

**Issue by formerhermit** [topcoderinc/umbrella_city#33]
Would it be possible to make the budget text red or have a minus sign in front of it instead of brackets, to make it more obvious it's in the red?
![budget](https://cloud.githubusercontent.com/assets/18323317/14977220/1e8966bc-110a-11e6-99fc-6d98b5f48887.PNG)

**Comment by formerhermit** [comment]
Thanks @RiteshAppirio could we make the red #fe5c5c? It's a bit lighter and easier to red on the grey. Thanks so much :)

**Comment by RiteshTC** [comment]
@formerhermit The color is now changed
