### ISSUE TITLE
CSS: Icons shift when trophy/Block cost appears

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#4]
When you hover over a building the trophy and Block Cost appears, and the icons to the right of the trophy skip a little bit to the right.

![screen shot 2016-04-06 at 5 00 06 pm](https://cloud.githubusercontent.com/assets/1180747/14334352/76d31ada-fc19-11e5-9638-fba1c50a6e96.png)

Simple css fix

**Comment by kbowerma** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30053764/?type=develop&noncache=true

**Comment by formerhermit** [comment]
This is fixed.
