### ISSUE TITLE
First time Popup

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#40]
This is a breakout from #11 

> Introduction Popup Text
> Welcome to Lillytropolis! You are a city architect who has been employed to modernise the city, we’ve given you a starting budget, so spend this wisely! Click on grey buildings to answer questions and refurbish your city to a future state. The closer your choices are to the overall strategy, the more money you will earn. However, be warned that poor choices can also have consequences! 
>  

This text / popup should be displayed the first time the user plays the game right after the city loads.    Maybe this can be triggered by creation of the user-score object or even a comparison of the budget to the starting budget.

**Comment by ThomasGriffinx** [comment]
@kbowerma @RiteshAppirio  @formerhermit  I think that keeping it simple is king here, 

Perhaps we should show the rules and intro text to the user the first time that they login,  then they can view the rules whenever they want via the nav bar  -  It wouldnt add much more value to the overall game with doing it any other way 

The actual wording of the Rules  - we can touch on this tonight in the meeting , I should have an update on it for then

**Comment by formerhermit** [comment]
@ThomasGriffinx This was a requirement from the US team - Kris said this was a thing she wanted. We can discuss. :)

**Comment by kbowerma** [comment]
@RiteshAppirio can you add the link to the rules and to start the game on the popup.

**Comment by RiteshTC** [comment]
Implemented. Is shown when there is no game user record found. To see, please delete your game user record and launch the game.

![titlepopup](https://cloud.githubusercontent.com/assets/5771673/15112239/71505022-160a-11e6-8190-3d6d97219116.png)

**Comment by formerhermit** [comment]
This is great, thanks! :)
