### ISSUE TITLE
Get AD groups to make permission sets.

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#41]
@formerhermit and Thom we need the AD groups for the admins and Players so we can get the permission sets created.

**Comment by ThomasGriffinx** [comment]
@kbowerma @formerhermit  Let me work with the US team to get this info , Ill send the mails today

**Comment by ThomasGriffinx** [comment]
@kbowerma @formerhermit @RiteshAppirio   Sent, I am waiting for response, will update when I hear

**Comment by ThomasGriffinx** [comment]
@kbowerma @formerhermit I will have more info on this tomorrow, I had a reply today

**Comment by formerhermit** [comment]
@ThomasGriffinx I spoke briefly to Sukrit about this on Friday, did this request get filled - I think I gave him everything he needed. Believe this is the last piece we need to get in place?

**Comment by ThomasGriffinx** [comment]
@formerhermit @kbowerma @RiteshAppirio  The last piece we need is for the topcoder guys to be added to the Lilly Repo so we can get the source code built with the CI auto stuff from our git, Ive just pinged the powers that be and been given a name, ill cc you @formerhermit  on the mail.

**Comment by kbowerma** [comment]
I have access to cloud bees and github so I should see it when created

**Comment by formerhermit** [comment]
All done, closed.
