### ISSUE TITLE
CSS: Text Sizing

### ISSUE THREAD

**Issue by formerhermit** [topcoderinc/umbrella_city#45]
@kbowerma Text in the question box for the mobile view is disproportionally smaller than text in answer boxes
![tiny text](https://cloud.githubusercontent.com/assets/18323317/15140159/c9ebbdac-1691-11e6-8071-e08ba75b091b.PNG)

**Comment by kbowerma** [comment]
@formerhermit and @ThomasGriffinx  @JGeeks fixed #45, #38, #34, and #6 can you take a look at close them if they look ok.

**Comment by formerhermit** [comment]
This one is fixed.
