### ISSUE TITLE
CSS: add helper submit text

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#5]
When you select and answer it is not very intuitive that you need to click the green checkbox to continue.   Add some text near the green checkbox that tells you to click it in order to submit.  Also on the opposite back button Icon add some hover text to go back to the city map.

![screen shot 2016-04-06 at 5 06 35 pm](https://cloud.githubusercontent.com/assets/1180747/14334439/14deb5fe-fc1a-11e5-9cff-9a48e2d4a665.png)

**Comment by formerhermit** [comment]
This is fixed
