### ISSUE TITLE
CSS: Question long text needs formatting

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#6]
Block 0-0-0 represents a very long question and the text scrolls off the page,    We need an elegant way to adjust for a long question with either a scroll or scaling.  Please provide suggestions for approval to address this.
![screen shot 2016-04-06 at 5 15 26 pm](https://cloud.githubusercontent.com/assets/1180747/14334624/2f6bc8de-fc1b-11e5-94a7-655441ea3e40.png)

**Comment by RiteshAppirio** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30053741/?type=develop&noncache=true

**Comment by RiteshTC** [comment]
![issue](https://cloud.githubusercontent.com/assets/5771673/14434453/7261d246-0030-11e6-81c9-f712ec68391f.png)

The solution option can expand their area as well. It needs to be fixed as well

**Comment by ThomasGriffinx** [comment]
@kbowerma @formerhermit @RiteshAppirio  This is going to be handled as part of the big CSS fix right ?

**Comment by kbowerma** [comment]
lets do this in the CSS fix

**Comment by ThomasGriffinx** [comment]
@kbowerma @RiteshAppirio @formerhermit 
![unnamed](https://cloud.githubusercontent.com/assets/16575724/15145653/ce2569be-16ae-11e6-9fe3-b6ff747d7720.png) can we swap those scroll bars for a styled arrow, pointing down at the bottom of the box? can use this one:
![snip20160510_1](https://cloud.githubusercontent.com/assets/16575724/15145711/1c4adbb0-16af-11e6-850a-6cb19e1509d2.png)
just rotate it so its facing down

**Comment by formerhermit** [comment]
This one looks much better @kbowerma @JGeeks @ThomasGriffinx I struggled to get the arrows to work on an ipad though (Was the actual scenario text rather than the choice boxes if that helps)

**Comment by ThomasGriffinx** [comment]
Awesome, Thanks @JGeeks  @kbowerma  @formerhermit
