### ISSUE TITLE
Convert penalty for wrong answer from static $ to % of winnings

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#7]
What percentage should we use?

**Comment by formerhermit** [comment]
On top of not getting their money back that they paid to play, they should lose an additional 25% of that cost:
e.g. Paid £1000 to play = lose all of that plus £250

**Comment by kbowerma** [comment]
is block cost is 7000 and users put in wrong answer they not only loose 7000 but also loose 25% of 7000 or (1750)    aka in math terms subtract 1.25 \* cost

**Comment by kbowerma** [comment]
@RiteshAppirio,   I assigned this to you, you can do a F2F, code challenge or do the work yourself.   Which every you prefer.

**Comment by formerhermit** [comment]
@kbowerma Please note there is also a payout calculation as in #12 Scoring Rule post (Cannot tag, github hates me)

**Comment by kbowerma** [comment]
Good catch I will update #12 based on our discussion yesterday

**Comment by formerhermit** [comment]
This is covered in issue 12.
